version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=trinca
      - POSTGRES_USER=root
      - POSTGRES_DB=trinca
  app:
    build: .
    volumes:
      - ./:/app
    ports:
      - 3333:3333
    depends_on:
      - postgres